from tkinter import  *
root=Tk()
root.title("Front Page")
root.geometry("2000x2000")
img=PhotoImage(file="starbus.png")
Label(root,image=img).pack(side=TOP)
Label(root,text="Online Bus Booking System",bg="grey",fg="red",font="Arial 20 bold").pack()
Label(root,text='\n\n').pack()
Label(root,text="NAME: VARUN PAREEK",font="Arial 14",fg="blue").pack(pady=20)
Label(root,text="Er: 221B434",font="Arial 14",fg="blue").pack(pady=20)
Label(root,text="Mobile: 9303959118",font="Arial 14",fg="blue").pack(pady=20)
Label(root,text='\n\n').pack()
Label(root,text="Sumitted to : Dr. Mahesh Kumar",bg="grey",fg="red",font="Arial 20 bold").pack()
Label(root,text="Project Based Learning",fg="red",font="Arial 12")
root.bind('<Key>',options)
root.mainloop()
